### ISSUE TITLE
Dúvidas sobre avaliação do desafio

### ISSUE THREAD

**Issue by devlucaslopes** [warrenbrasil/desafio-warren-web#2]
Meu nome é Lucas, faço lives de programação na Twitch para tentar ajudar outras pessoas que gostariam de começar na área.

Durante algumas lives resolvi fazer o desafio para mostrar as pessoas com menos experiência como são esses processos e também como isso pode ser muito muito para aprendizado/treino. 

Gostaria de saber se vocês poderiam avaliar o meu projeto...Quero mostrar os feedbacks durante as lives e conversar sobre cada ponto com as pessoas.

Link do meu projeto: https://github.com/devlucaslopes/challenge-warren-front-end
Aqui estão todas as lives que fiz sobre o desafio: https://twitch.tv/devlucaslopes

Obrigado pela atenção!

**Comment by pepoeverton** [comment]
Opa Lucas, tudo bem? Mil desculpas ao demorar em te retornar aqui nessa _issue_!!!

Primeiramente obrigado pelo tempo que teve ao fazer o desafio e com certeza vamos dar uma boa olhada no teu projeto e também nas tuas lives!!! Entre hoje e amanhã vamos te enviar os feedbacks em relação ao desafio, tudo bem?


Abraço e tenha um bom dia!

**Comment by devlucaslopes** [comment]
@pepoeverton muito obrigado pela atenção e aguardo seu retorno <3
